### ISSUE TITLE
reformat Dingens et al 2019 to match IAV format

### ISSUE THREAD

**Issue by skhilton** [dms-view/HIV#2]
The current data for the Antigenic Atlas should look like https://github.com/dms-view/influenza

**Comment by skhilton** [comment]
@jbloom: Could you take a look at this and make sure it has information you think is important for these dataset specific directories?

https://github.com/dms-view/HIV/tree/master/data/Env/Dingens2019

**Comment by jbloom** [comment]
Looks good to me.
