### ISSUE TITLE
Add HIV rabbit serum mapping data 

### ISSUE THREAD

**Issue by skhilton** [dms-view/HIV#3]

**Comment by skhilton** [comment]
Here is the link https://dms-view.github.io/?markdown-url=https%3A%2F%2Fraw.githubusercontent.com%2Fdms-view%2FHIV%2Fmaster%2Fdata%2FEnv%2FDingens2020%2FDingens2020.md&data-url=https%3A%2F%2Fraw.githubusercontent.com%2Fdms-view%2FHIV%2Fmaster%2Fdata%2FEnv%2FDingens2020%2FDingens2020.csv&condition=2124-Wk22&site_metric=site_positive+diffsel+%28median+of+reps%29&mutation_metric=mut_mut+pos+diffsel+%28median+of+reps%29&selected_sites=464&pdb-url=https%3A%2F%2Fraw.githubusercontent.com%2Fdms-view%2FHIV%2Fmaster%2Fdata%2FEnv%2FDingens2020%2F5FYL_AbsRemoved.pdb

**Comment by skhilton** [comment]
@adingens Could you review that this all looks okay? I added back in the insertion sites like 322a

**Comment by skhilton** [comment]
Here is the new link

https://dms-view.github.io/?markdown-url=https%3A%2F%2Fraw.githubusercontent.com%2Fdms-view%2FHIV%2Fmaster%2Fdata%2FEnv%2FDingens2020%2FDingens2020.md&data-url=https%3A%2F%2Fraw.githubusercontent.com%2Fdms-view%2FHIV%2Fmaster%2Fdata%2FEnv%2FDingens2020%2FDingens2020.csv&condition=2124-Wk22&site_metric=site_positive+diffsel+%28median+of+reps%29&mutation_metric=mut_mut+pos+diffsel+%28median+of+reps%29&selected_sites=85%2C88%2C90%2C229%2C230%2C347%2C350%2C354%2C356%2C358%2C460%2C462%2C463%2C464%2C465%2C624%2C629%2C630&pdb-url=https%3A%2F%2Fraw.githubusercontent.com%2Fdms-view%2FHIV%2Fmaster%2Fdata%2FEnv%2FDingens2020%2F5fyl_monomer_renumber.pdb

**Comment by adingens** [comment]
Yes, this is corrected in both the rabbit sera and antigenic atlas datasets.
